tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "bat"
brew "fzf"
brew "git"
brew "git-delta"
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "autojump"
brew "zsh-completions"
