tap "homebrew/cask-fonts"

# Used as the fallback font for kitty, for all the symbols
cask "font-inconsolata-nerd-font"

cask "font-ibm-plex-mono"
cask "font-jetbrains-mono"
cask "font-cascadia-mono"
cask "font-lekton"
cask "font-iosevka-curly"
cask "font-go"
cask "font-overpass-mono"

